version: '3'

services:

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    env_file:
      - .env
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8080"
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
